from types import SimpleNamespace

from flag_recognition import llm_backend


class _RateLimitError(RuntimeError):
    status_code = 429

    def __init__(self, retry_after="0"):
        super().__init__("rate_limit_exceeded")
        self.response = SimpleNamespace(headers={"retry-after": retry_after})


class _FakeResponses:
    def __init__(self, outcomes):
        self.outcomes = list(outcomes)
        self.calls = []

    def create(self, **kwargs):
        self.calls.append(kwargs)
        outcome = self.outcomes.pop(0)
        if isinstance(outcome, Exception):
            raise outcome
        return SimpleNamespace(output_text=outcome)


def test_rate_limit_waits_and_retries(monkeypatch):
    sleeps = []
    raw = _FakeResponses([_RateLimitError("0"), "ok"])
    resilient = llm_backend._ResilientResponses(raw, backend="groq")

    monkeypatch.setattr(llm_backend.time, "sleep", sleeps.append)

    response = resilient.create(model="openai/gpt-oss-20b", input="hello")

    assert response.output_text == "ok"
    assert len(raw.calls) == 2
    assert sleeps


def test_rate_limit_switches_to_backup_model(monkeypatch):
    raw = _FakeResponses([
        _RateLimitError("0"),
        _RateLimitError("0"),
        "backup ok",
    ])
    resilient = llm_backend._ResilientResponses(raw, backend="groq")

    monkeypatch.setattr(llm_backend.time, "sleep", lambda _: None)
    monkeypatch.setenv(
        "FLAG_INTELLIGENCE_GROQ_FALLBACK_MODEL",
        "openai/gpt-oss-120b",
    )

    response = resilient.create(
        model="openai/gpt-oss-20b",
        input="hello",
    )

    assert response.output_text == "backup ok"
    assert raw.calls[-1]["model"] == "openai/gpt-oss-120b"


def test_review_rate_limit_keeps_model_generated_draft(monkeypatch):
    raw = _FakeResponses([_RateLimitError("0")] * 4)
    resilient = llm_backend._ResilientResponses(raw, backend="groq")

    monkeypatch.setattr(llm_backend.time, "sleep", lambda _: None)
    monkeypatch.setenv(
        "FLAG_INTELLIGENCE_GROQ_FALLBACK_MODEL",
        "openai/gpt-oss-120b",
    )

    response = resilient.create(
        model="openai/gpt-oss-20b",
        input=[
            {"role": "system", "content": "Review it."},
            {
                "role": "user",
                "content": "DRAFT SECTION:\nThis was already generated by the model.",
            },
        ],
        tools=[{"type": "browser_search"}],
        tool_choice="auto",
    )

    assert response.output_text == "This was already generated by the model."
